TebLocalPlannerROS:
  odom_topic: odom

  # Robot

  max_vel_x: 0.5
  max_vel_x_backwards: 0.5
  max_vel_y: 0.0
  max_vel_theta: 0.4
  acc_lim_x: 0.5
  acc_lim_theta: 0.3
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    type: "polygon"
    vertices:
      [[0.513, 0.364], [0.513, -0.364], [-0.513, -0.364], [-0.513, 0.364]]

  # GoalTolerance

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15
  free_goal_vel: False
  complete_global_plan: True

  # Recovery

  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
