DWAPlannerROS:

  # params are from https://github.com/dietriro/rto_core/tree/noetic-devel/rto_navigation/config
  # and https://www.robotshop.com/media/files/content/f/fto/pdf/festo-robotino-mobile-robotic-datasheet.pdf

  # Robot Configuration Parameters
  max_vel_x: 0.8
  min_vel_x: 0.0

  max_vel_y: 0.8
  min_vel_y: 0.1

  # The velocity when robot is moving in a straight line
  max_vel_trans: 0.8
  min_vel_trans: .1

  max_rot_vel: 1.2
  min_rot_vel: 0.1

  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2

  # Goal Tolerance Parametes
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 5.0

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Debugging
  publish_traj_pc: true
  publish_cost_grid_pc: true
