# TODO: The discrete actions have not been changed (from ridgeback here)
# values from: https://github.com/youbot/youbot_navigation/blob/hydro-devel/youbot_navigation_common/config/base_local_planner_params.yaml
# and values from here: http://www.youbot-store.com/wiki/index.php/YouBot_Detailed_Specifications
robot:
  holonomic: True
  discrete_actions:
    - name: move_forward
      linear: 2.78
      angular: 0.0
    - name: move_backward
      linear: -0.15
      angular: 0.0
    - name: turn_left
      linear: 0.15
      angular: 0.35
    - name: turn_right
      linear: 0.15
      angular: -0.35
    - name: turn_strong_left
      linear: 0.0
      angular: 0.75
    - name: turn_strong_right
      linear: 0.0
      angular: -0.75
    - name: stop
      linear: 0.0
      angular: 0.0
  continuous_actions:
    linear_range: 
      x: [-0.8, 0.8] # Maximum translational velocity in [m/s]
      y: [-0.8, 0.8]
    angular_range: [-1.2, 1.2] # Maximum rotational velocity in [rad/s]