obstacle_range: 3.5
raytrace_range: 3.0

footprint: [[-0.21, -0.21], [-0.21, 0.21], [0.21, 0.21], [0.21, -0.21]]
# radius: 0.267 from (0.21**2+0.21**2)**(1/2)



inflation_radius: 8.0
cost scaling factor: 7.58


map_type: costmap
# needed for the VoxelCostmapPlugin: http://wiki.ros.org/costmap_2d/hydro/obstacles
# NOTE: Good Documentation on Voxel https://kaiyuzheng.me/documents/navguide.pdf
# SUMMARY: Voxel-grid enables obstacle modeling in 3D; next to laser scan data, depth sensors are requiered 
origin_z: 0.0
z_resolution: 1
z_voxels: 2
publish_voxel_map: false

transform_tolerance: 0.5
meter_scoring: true


# plugins:
# - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
# - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

<<<<<<< HEAD
obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 2.5, raytrace_range: 3.0}

=======
>>>>>>> origin/noetic-devel

observation_sources: scan
scan: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}