map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[0.2755, -0.2585], [0.2755, 0.2585], [-0.2755, 0.2585], [-0.2755, -0.2585]]
# RADIUS: 0.378 from (0.2755**2 + 0.2585**2)**(1/2)
footprint_padding: 0.1

plugins:
  - { name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
  - { name: inflater_layer, type: "costmap_2d::InflationLayer" }

obstacles_layer:
  observation_sources: scan
  scan:
    {
      sensor_frame: laser_link, #front_laser
      data_type: LaserScan,
      topic: scan,
      marking: true,
      clearing: true,
      obstacle_range: 2.5,
      raytrace_range: 3.0,
    }

inflater_layer:
  inflation_radius: 1.0
