DWAPlannerROS:
  # params are from https://github.com/pal-robotics/pal_navigation_cfg_public/blob/master/pal_navigation_cfg_pmb2/config/base/dwa/local_planner.yaml
  # Robot Configuration Parameters
  max_vel_x: 1.5
  min_vel_x: 0

  max_vel_y: 0.0
  min_vel_y: 0.0

  # The velocity when robot is moving in a straight line
  max_vel_trans: 1.5
  min_vel_trans: 0.1

  max_vel_theta: 2.0
  min_vel_theta: 0.4

  acc_lim_x: 0.8
  acc_lim_y: 0.0
  acc_lim_theta: 1.5

  # Goal Tolerance Parametes
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.7
  vx_samples: 10
  vy_samples: 0
  vth_samples: 20
  controller_frequency: 10.0

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 1.0
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.1

  # Debugging
  publish_traj_pc: true
  publish_cost_grid_pc: true