robot:
  holonomic: False
  discrete_actions:
    - name: move_forward
      linear: 1.3
      angular: 0.0
    - name: move_backward
      linear: -1.0
      angular: 0.0
    - name: turn_left
      linear: 0.75
      angular: 0.35
    - name: turn_right
      linear: 0.75
      angular: -0.35
    - name: turn_strong_left
      linear: 0.0
      angular: 0.75
    - name: turn_strong_right
      linear: 0.0
      angular: -0.75
    - name: stop
      linear: 0.0
      angular: 0.0
  continuous_actions:
    linear_range: [-1.3, 1.3] # Maximum translational velocity in m/s
    angular_range: [-2.35619, 2.35619] # Maximum rotational velocity in rad/s
